config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  get '/users/sign_out', to: 'devise/sessions#destroy'
  delete '/users/sign_out', to: 'devise/sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  get 'posts' => 'posts#index'
  get 'posts/new' => 'posts#new'
  post 'posts' => 'posts#create'
  get 'posts/:id' => 'posts#show',as: 'post'
  patch 'posts/:id' => 'posts#update'
  delete 'posts/:id' => 'posts#destroy'
  get 'posts/:id/edit' => 'posts#edit', as:'edit_post'
  root 'hello#index'
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         mount_uploader :image, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
  has_many :comments, dependent: :destroy
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      # deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.build(comment_params) #buildを使い、contentとpost_idの二つを同時に代入
    comment.user_id = current_user.id
    if comment.save
      flash[:success] = "コメントしました"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    else
      flash[:success] = "コメントできませんでした"
      redirect_back(fallback_location: root_path) #直前のページにリダイレクト
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
    def index
      @posts = Post.all
      search = params[:search]
      @posts = @posts.joins(:user).where("title LIKE ? OR email LIKE ?", "%#{search}%", "%#{search}%") if search.present?
    end
    def new
        @post = Post.new
    end
    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
      @post = Post.find(params[:id])
      @comments = @post.comments
        @comment = Comment.new
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      post = Post.find(params[:id])
      if post.update(post_params)
        redirect_to :action => "show", :id => post.id
      else
        redirect_to :action => "new"
      end
    end

    def destroy
      post = Post.find(params[:id])
      post.destroy
      redirect_to action: :index
    end
  
    
      private
      def post_params
        params.require(:post).permit(:body, :title, :image)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>
<div class="textarea">
<%= link_to "ログイン", posts_path %>
<%= link_to "新規登録", new_user_registration_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manualist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/46e8a54dae.js" crossorigin="anonymous"></script>    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Manualist</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", posts_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "新規投稿",posts_new_path %></li>
        <li><%= link_to "マイページ",user_path(current_user.id)%></li>
        <% end %>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :title %>
      <%= f.text_field :title, :size => 140 %>
      <br>
    <%= f.label :image %>
      <%= f.file_field :image %>
      <br>
    <%= f.label :body %>
      <%= f.text_field :body, :size => 140 %> 
      <br>
    <%= f.submit "編集する" %>
  <% end %>

app/views/posts/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="search">
  <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <%= text_field_tag :search %>
  <div class="button">
  <%= submit_tag '検索'  %>
  </div>
<% end %>
</div>


<h3>記事一覧</h3>
<div class="posts-container">
  <% @posts.each do |t| %>
    <div class="post">
    <%= image_tag t.user.image_url, size: "40x30" if t.user.image? %>
    <%= link_to t.user.name, user_path(t.user.id) %>
    <%= t.user.email %>
      <div class="main-box">
        <div class="left-container">
          <%= t.title %>

          <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

          <%= image_tag t.image_url, size: "100x100" if t.image? %>
        </div>
        <div class="right-container">
          <%= link_to "詳細", post_path(t.id) %>
          <%= link_to "編集", edit_post_path(t.id) %>
          <%= button_to "削除", post_path(t.id), method: :delete %>
        </div>
      </div>
        <p class="time"><%= t.created_at %></p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, local: true do |f| %>
<%= stylesheet_link_tag 'new', :media => "all" %>

<div class="post-container">
    <p class="title">投稿フォーム</p>
    <%= form_for(@post, :url => { controller:'posts', action:'create'})do |f| %>
    <%= f.label :記事タイトル %>
        <br>
        <%= f.text_field :title,size: 140%>
        <%= f.label :image %>
            <%= f.file_field :image %>
        <br>
        <%= f.text_field :body,size: 140%>

    <%= f.submit "送信"%>
    <br>
    <% end %>
</div>
<% end %>

app/views/posts/show.html.erb
<h3>記事詳細</h3>
<div class="textarea">
<div class="post">

  <p><%= @post.title %></p>
  <p><%= image_tag @post.image_url, size: "250x200" %></p>
  <p><%= @post.body %></p>
  <p><%= @post.created_at %></p>
</div>

<% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
        <%= button_to post_like_path(@post), method: :delete do %>
          <p>いいねを取り消す</p><%= @post.likes.count %>
        <% end %>
      <% else %>
        <%= button_to post_likes_path(@post), method: :post do %>
          <p>いいね</p><%= @post.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @post.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_post_path(@post.id) %>


<p><h2>いいねしたユーザー</h2></p>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "記事一覧に戻る", posts_path %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

<div class="textarea">
<h1>マイページ</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
<%= image_tag @user.image_url, size: "250x200" if @user.image? %>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>

<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_posts.each do |t| %>
  <%= t.user.name %>
  <%= t.body %>
<% end %>
<!-- ここまで-->

<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>


<%= link_to "記事一覧に戻る", posts_path %>
</div>